### PR TITLE
CH11 over Ether

### PR DESCRIPTION
**Pull request by bictorv**
Implemented Chaosnet-over-Ethernet (in addition to Chaos-over-UDP), using libpcap.

### CODE REVIEW

**Review by Rhialto — APPROVED** [review]
I'm not set up to test this myself, but what I see in the diffs looks good to me, and is quite useful. So go ahead, I say!

**Review by larsbrinkhoff — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Is this compatible with Lisp machine networking?

CC @ams

**Comment by bictorv** [comment]
It is "directly" compatible with LambdaDelta (the LMI Lambda emulator), and through the Chaosnet bridge also with usim (the CADR emulator). I haven't actually double-checked the compatibility with the old Symbolics 3650, since it's so hard to use without a working screen, but it "should work".

**Comment by larsbrinkhoff** [comment]
Cool, thanks.

I'll take this opportunity to mention I'm writing an IMP workalike.  It should interface to SIMH, Ethernet, and virtal connections to other IMPs.  It actually shares many properties with the Chaosnet bridge, so I'll probably be looking for inspiration there.

**Comment by bictorv** [comment]
I plan to rewrite the bridge using libpcap, which would save a lot of effort I think. Also, I need to implement something else than UDP, since my ISP just stopped giving me a public IP, which breaks incoming UDP connectivity.

**Comment by larsbrinkhoff** [comment]
I think TCP will be appropriate for the IMP links.  They used to talk over leased phone lines, with a packet protocol on top of that.  (But maybe these days HTTPS is the new universal transport layer, shudder.  With JSON payload, I'm sure.)

**Pull request merged**
