### PR TITLE
Add Chaosnet device

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
@bictorv has code to add a functional Chaosnet network device.  This pull request integrates that code.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Added files, applied patch, fixed conflicts.  It builds.

**Comment by larsbrinkhoff** [comment]
Not tested, but there was no visible bit-rot so it must work as-is, right?

**Comment by Rhialto** [comment]
Is it ok if I look at this after the weekend?

**Comment by larsbrinkhoff** [comment]
Absolutely!

**Review by Rhialto — APPROVED** [review]
I could not resist having a peek and it was way simpler (in terms of structure changing) than I thought so there isn't much I could say against it :-)

**Comment by larsbrinkhoff** [comment]
Yes, it seems quite safe to merge.

@eswenson1, have you used Chaosnet?

**Comment by eswenson1** [comment]
No, not yet.

**Pull request merged**
